[package]
name = "rustis"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "2.10.0"
actix-web = "4.9.0"
askama = "0.12.1"
chrono = "0.4.38"
serde = "1.0.210"
serde_json = "1.0.128"
thiserror = "1.0.64"
